# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS/7"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  # vm config
 
  (0..2).each do |n|
    config.vm.define "m7-autocv-gpu0#{n+1}" do |c|
        c.vm.hostname = "m7-autocv-gpu0#{n+1}"
        c.vm.network "private_network", ip: "172.27.128.#{150-n}"

        #c.vm.provision :shell, :path => "scripts/vagrant-setup-hosts-file.bash"

        c.vm.provider "virtualbox" do |vb|
          vb.memory = "640"
        end
    end
  end
end
